"""Add country field with default

Revision ID: 929eee5211b2
Revises: ed8ae7166486
Create Date: 2026-04-23 06:40:24.205234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '929eee5211b2'
down_revision: Union[str, Sequence[str], None] = 'ed8ae7166486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add country column as nullable first
    op.add_column('threat_logs', sa.Column('country', sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE threat_logs SET country = 'Unknown' WHERE country IS NULL")
    # Make it non-nullable
    op.alter_column('threat_logs', 'country', nullable=False, server_default='Unknown')
    
    # Fix created_at for existing NULL values
    op.execute("UPDATE threat_logs SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column('threat_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('NOW()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('threat_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('threat_logs', 'country')
    # ### end Alembic commands ###
